// Enhanced export utilities combining myjuris + courtscribe-nexus features
// Supports PDF reports with adjournment tracking

import jsPDF from 'jspdf';
import type { Marker, Note, Adjournment } from './types-adjournment';
import type { Bookmark, TranscriptSegment } from './types';

interface SessionExportData {
  caseName: string;
  suitNumber: string;
  plaintiff: string;
  defendant: string;
  startedAt: string;
  durationSeconds: number;
}

interface EnhancedExportData extends SessionExportData {
  markers: Marker[];
  notes: Note[];
  adjournments: Adjournment[];
  transcript: TranscriptSegment[];
  bookmarks: Bookmark[];
}

const formatTimestamp = (ms: number) => {
  const mins = Math.floor(ms / 60000);
  const secs = Math.floor((ms % 60000) / 1000);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

const formatDate = (date: Date | string) => {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

const formatTime = (seconds: number) => {
  const hours = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = seconds % 60;
  
  if (hours > 0) {
    return `${hours}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

/**
 * Export enhanced session report to PDF
 * Combines transcript, bookmarks, markers, notes, and adjournments
 */
export async function exportEnhancedPDF(data: EnhancedExportData): Promise<Blob> {
  const pdf = new jsPDF();
  
  let yPos = 20;
  const pageHeight = pdf.internal.pageSize.height;
  const margin = 20;
  const lineHeight = 7;
  
  const checkNewPage = (requiredSpace: number = 20) => {
    if (yPos + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPos = 20;
    }
  };

  // Header
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Court Session Report', margin, yPos);
  yPos += 12;

  // Generated by
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(128, 128, 128);
  pdf.text(`Generated by myJuris on ${formatDate(new Date())}`, margin, yPos);
  pdf.setTextColor(0, 0, 0);
  yPos += 15;

  // Session details
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Session Details', margin, yPos);
  yPos += lineHeight + 2;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  pdf.text(`Case: ${data.caseName}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Suit Number: ${data.suitNumber}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Plaintiff: ${data.plaintiff}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Defendant: ${data.defendant}`, margin, yPos);
  yPos += lineHeight;
  
  pdf.text(`Date: ${formatDate(data.startedAt)}`, margin, yPos);
  yPos += lineHeight;
  pdf.text(`Duration: ${formatTime(data.durationSeconds)}`, margin, yPos);
  yPos += 15;

  // Transcript section
  if (data.transcript.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Transcript (${data.transcript.length} segments)`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    
    data.transcript.forEach((seg) => {
      checkNewPage(10);
      const timestamp = `[${formatTimestamp(seg.startMs)}]`;
      const speaker = `${seg.speaker}:`;
      pdf.text(`${timestamp} ${speaker}`, margin, yPos);
      
      // Wrap text
      const maxWidth = pdf.internal.pageSize.width - margin * 2 - 30;
      const splitText = pdf.splitTextToSize(seg.text, maxWidth);
      yPos += lineHeight - 1;
      
      splitText.forEach((line: string) => {
        checkNewPage();
        pdf.text(line, margin + 15, yPos);
        yPos += lineHeight - 1;
      });
      yPos += 2;
    });
    yPos += 5;
  }

  // Bookmarks section
  if (data.bookmarks.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Bookmarks (${data.bookmarks.length})`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    data.bookmarks.sort((a, b) => a.timeMs - b.timeMs).forEach((bookmark) => {
      checkNewPage();
      pdf.text(`[${formatTimestamp(bookmark.timeMs)}] ${bookmark.label}`, margin, yPos);
      yPos += lineHeight;
    });
    yPos += 8;
  }

  // Markers section
  if (data.markers.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Markers (${data.markers.length})`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    data.markers.sort((a, b) => a.timestampMs - b.timestampMs).forEach((marker) => {
      checkNewPage();
      pdf.text(`[${formatTimestamp(marker.timestampMs)}] ${marker.label}`, margin, yPos);
      yPos += lineHeight;
    });
    yPos += 8;
  }

  // Notes section
  if (data.notes.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Notes (${data.notes.length})`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    data.notes.sort((a, b) => a.timestampMs - b.timestampMs).forEach((note) => {
      checkNewPage(20);
      const timestamp = `[${formatTimestamp(note.timestampMs)}]`;
      pdf.text(timestamp, margin, yPos);
      
      const maxWidth = pdf.internal.pageSize.width - margin * 2;
      const splitText = pdf.splitTextToSize(note.content, maxWidth - 30);
      yPos += lineHeight;
      splitText.forEach((line: string) => {
        checkNewPage();
        pdf.text(line, margin + 10, yPos);
        yPos += lineHeight;
      });
      yPos += 3;
    });
    yPos += 5;
  }

  // Adjournments section
  if (data.adjournments.length > 0) {
    checkNewPage(30);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Adjournments (${data.adjournments.length})`, margin, yPos);
    yPos += lineHeight + 2;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    data.adjournments.sort((a, b) => a.timestampMs - b.timestampMs).forEach((adj) => {
      checkNewPage(25);
      pdf.text(`[${formatTimestamp(adj.timestampMs)}]`, margin, yPos);
      yPos += lineHeight;
      
      if (adj.nextDate) {
        pdf.text(`  Next Date: ${new Date(adj.nextDate).toLocaleDateString('en-NG')}`, margin, yPos);
        yPos += lineHeight;
      }
      if (adj.reason) {
        const maxWidth = pdf.internal.pageSize.width - margin * 2;
        const splitReason = pdf.splitTextToSize(`  Reason: ${adj.reason}`, maxWidth);
        splitReason.forEach((line: string) => {
          checkNewPage();
          pdf.text(line, margin, yPos);
          yPos += lineHeight;
        });
      }
      
      const confidenceText = adj.confidence === 'high' ? 'Confirmed' : 
                             adj.confidence === 'medium' ? 'Uncertain' : 
                             adj.confidence === 'unconfirmed' ? 'Unconfirmed' : 'Low Confidence';
      pdf.text(`  Confidence: ${confidenceText}`, margin, yPos);
      yPos += lineHeight + 5;
    });
  }

  // Footer
  checkNewPage(20);
  yPos = pageHeight - 15;
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('This report is for personal legal use. Generated by myJuris.', margin, yPos);

  return new Promise((resolve) => {
    pdf.save(`${data.suitNumber}_report.pdf`);
    // Get PDF as blob
    const blob = pdf.output('blob') as Blob;
    resolve(blob);
  });
}

/**
 * Export audio file
 */
export async function exportAudio(audioBlob: Blob, fileName: string): Promise<void> {
  const url = URL.createObjectURL(audioBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export session data as markdown
 */
export async function exportMarkdown(data: EnhancedExportData): Promise<Blob> {
  let content = `# Court Session Notes\n\n`;
  content += `**Generated by myJuris on ${formatDate(new Date())}**\n\n`;
  content += `---\n\n`;
  
  content += `## Session Details\n\n`;
  content += `- **Case:** ${data.caseName}\n`;
  content += `- **Suit Number:** ${data.suitNumber}\n`;
  content += `- **Plaintiff:** ${data.plaintiff}\n`;
  content += `- **Defendant:** ${data.defendant}\n`;
  content += `- **Date:** ${formatDate(data.startedAt)}\n`;
  content += `- **Duration:** ${formatTime(data.durationSeconds)}\n\n`;

  if (data.markers.length > 0) {
    content += `## Markers\n\n`;
    data.markers.sort((a, b) => a.timestampMs - b.timestampMs).forEach((m) => {
      content += `- [${formatTimestamp(m.timestampMs)}] ${m.label}\n`;
    });
    content += `\n`;
  }

  if (data.notes.length > 0) {
    content += `## Notes\n\n`;
    data.notes.sort((a, b) => a.timestampMs - b.timestampMs).forEach((n) => {
      content += `### [${formatTimestamp(n.timestampMs)}]\n${n.content}\n\n`;
    });
  }

  if (data.adjournments.length > 0) {
    content += `## Adjournments\n\n`;
    data.adjournments.sort((a, b) => a.timestampMs - b.timestampMs).forEach((adj) => {
      content += `### [${formatTimestamp(adj.timestampMs)}]\n`;
      if (adj.nextDate) content += `- **Next Date:** ${new Date(adj.nextDate).toLocaleDateString('en-NG')}\n`;
      if (adj.reason) content += `- **Reason:** ${adj.reason}\n`;
      content += `- **Confidence:** ${adj.confidence}\n\n`;
    });
  }

  return new Blob([content], { type: 'text/markdown' });
}
